version: '2'

services:
    dashboard:
        build: ./images/php-apache
        image: supervisorg/demo/php-apache
        container_name: supervisorg-demo-dashboard
        volumes:
            - ./config/apache2/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
            - ../../:/var/www/supervisorg
        ports:
            - "80:80"
        links:
            - server-1
            - server-2
            - server-3
        environment:
            - USER_ID=${USER_ID}
            - GROUP_ID=${GROUP_ID}

    server-1:
        build: ./images/supervisord
        image: supervisorg/demo/supervisord
        container_name: supervisorg-demo-server-1
        volumes:
            - ./config/supervisor/server-1.conf:/etc/supervisor/conf.d/server.conf

    server-2:
        build: ./images/supervisord
        image: supervisorg/demo/supervisord
        container_name: supervisorg-demo-server-2
        volumes:
            - ./config/supervisor/server-2.conf:/etc/supervisor/conf.d/server.conf

    server-3:
        build: ./images/supervisord
        image: supervisorg/demo/supervisord
        container_name: supervisorg-demo-server-3
        volumes:
            - ./config/supervisor/server-3.conf:/etc/supervisor/conf.d/server.conf
